name       : haskell-happy
version    : 1.19.12
release    : 4
source     :
    - https://hackage.haskell.org/package/happy-1.19.12/happy-1.19.12.tar.gz : fb9a23e41401711a3b288f93cf0a66db9f97da1ce32ec4fffea4b78a0daeb40f
license    : BSD-3-Clause
component  : programming.haskell
summary    : Happy is a parser generator for Haskell.
description: |
    Happy is a parser generator for Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
