name       : haskell-happy
version    : 1.19.5
release    : 1
source     :
    - http://hackage.haskell.org/package/happy-1.19.5/happy-1.19.5.tar.gz : 62f03ac11d7b4b9913f212f5aa2eee1087f3b46dc07d799d41e1854ff02843da
license    : BSD-3-Clause
component  : programming
summary    : Happy is a parser generator for Haskell.
description: |
    Happy is a parser generator for Haskell.
builddeps  :
    - ghc
    - haskell-mtl
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    mv $installdir/usr/share/x86_64-linux-ghc-8.0.1 $installdir/usr/share/ghc-8.0.1