name       : haskell-happy
version    : 1.19.5
release    : 2
source     :
    - http://hackage.haskell.org/package/happy-1.19.5/happy-1.19.5.tar.gz : 62f03ac11d7b4b9913f212f5aa2eee1087f3b46dc07d799d41e1854ff02843da
license    : BSD-3-Clause
component  : programming.haskell
summary    : Happy is a parser generator for Haskell.
description: |
    Happy is a parser generator for Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-mtl-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
